### ISSUE TITLE
ara::core 데이터 타입 사용 불가

### ISSUE THREAD

**Issue by sykim-rtst** [sykim-rtst/rasp-rest#1]
ara::rest에서 사용하는 ara::core 데이터 타입을 사용할 수 없는 상황이므로, 별도로 ara::core 패키지를 구현하거나 이를 대체할 대상을 선정하여야 한다.

**Comment by yongjin-seo** [comment]
ara::core 패키지는 C++ 표준 라이브러리 기반으로 구현되었습니다.
따라서 별도의 ara::core 패키지를 구현하는 것보다는 C++ 표준 라이브러리를 활용하여 구현하는 것이 바람직하다고 판단하였습니다.

관련된 내용은 [Commit #bb38201](https://github.com/sykim-rtst/rasp-rest/commit/bb3820135b47074ed32e20d257747b7260688253) 을 확인하시기 바랍니다.
