### ISSUE TITLE
ara::rest::ogm Serialize 기능 개발 필요

### ISSUE THREAD

**Issue by sykim-rtst** [sykim-rtst/rasp-rest#2]
ara::rest::ogm::Serializer는 rapidjson을 기반으로 구현된 내용을 다른 json 라이브러리로 대체하거나 새로 개발할 필요가 있다.

**Comment by yongjin-seo** [comment]
JSON의 문법은 다른 언어에 비해 매우 간단하므로, 굳이 별도의 라이브러리를 사용하지 않기로 하였습니다.
Serialize 기능은 String to OGM, OGM to String 정도만 수행하면 되므로 String 파싱을 통해 ara::rest::ogm을 위한 Serialize 기능을 구현하였습니다.

추후 확장을 고려하여 동적으로 파서를 선택하도록 구현하였습니다. (JSON 파서, XML 파서 등)

관련된 내용은 [Commit #5e2eeed](https://github.com/sykim-rtst/rasp-rest/commit/5e2eeed32f955aa020429b725069467cd7ba28db) 을 확인하시기 바랍니다.
