### ISSUE TITLE
Protocol Binding Interface 구현

### ISSUE THREAD

**Issue by sykim-rtst** [sykim-rtst/rasp-rest#3]
AUTOSAR RESTful 명세에서 언급된 ara::rest의 Protocol Binding을 위해 Bridge 패턴을 구현할 필요가 있다.

**Comment by yongjin-seo** [comment]
Bridge 패턴을 적용하기 위해 Server와 Client를 위한 추상 인터페이스를 정의하였습니다.
각각은 ServerProtocolBinder와 ClientProtocolBinder로 명명하였습니다.

HTTP 기반의 통신을 지원하기 위해 각 추상 인터페이스를 상속받는 ServerHttpBinder와 ClientHttpBinder를 구현하였습니다. 현재 AUTOSAR에서 HTTP만을 사용하도록 정의되어 있으므로, 이 외의 Binder 클래스는 구현하지 않았습니다.

Bridge 패턴을 적용하였기 때문에, 표준이 확장되더라도 Binder 클래스만 추가 구현하면 되리라 생각됩니다.

관련 내용은 [Commit #a63141](https://github.com/sykim-rtst/rasp-rest/commit/a6314156c36362c9e27dfec6e38acce9fe1cea35)과 [Commit #de7f7fe](https://github.com/sykim-rtst/rasp-rest/commit/de7f7feac2698e9c959d8a98dd6c29ce7f45347e#diff-5741ae062baa4438640defae9ffb9c3e) 에서 확인하시기 바랍니다.
