### ISSUE TITLE
ara::rest::ogm 편의성 개선

### ISSUE THREAD

**Issue by sykim-rtst** [sykim-rtst/rasp-rest#4]
AUTOSAR RESTful 명세에 준하여 구현된 OGM은 사용하기 불편한 라이브러리에 해당된다.
ara::rest::ogm은 기존의 JSON 라이브러리를 참조하여 API가 설정되어 있지만, 저장된 값에 접근하기 어렵게 구성되어 있다.
가령, ogm::Array와 ogm::Object를 통해 얻는 값은 ogm::Value 형태로 전달받는다.
그러나 ogm::Value 내부의 값에 접근하기 위해서는 형 변환이 필수적이며 이마저도 제공되는 ogm::Visit 함수를 통해서만 가능하다.
일반적으로 JSON 라이브러리에서는 각 노드의 데이터 타입을 확인하기 위한 API와 각 데이터 타입에 맞게 값을 전달받거나 수정할 수 있는 API를 제공한다.
AUTOSAR RESTful 명세에서는 이와 같은 내용을 고려하지 않으므로 이에 대해 확장 구현이 필요하다.

**Comment by yongjin-seo** [comment]
각 노드의 데이터 타입을 확인할 수 있는 API를 추가하였습니다. 

관련 내용은 [Commit #5e2eeed](https://github.com/sykim-rtst/rasp-rest/commit/5e2eeed32f955aa020429b725069467cd7ba28db)
